export const enum FontsOSANS {
    OSANS_CONDENSED_BOLD = 'OpenSans_Condensed-Bold',
    OSANS_CONDENSED_ITALIC = 'OpenSans_Condensed-Italic',
    OSANS_CONDENSED_BOLD_ITALIC = 'OpenSans_Condensed-BoldItalic',
    OSANS_CONDENSED_EXTRA_BOLD = 'OpenSans_Condensed-ExtraBold',
    OSANS_CONDENSED_EXTRA_BOLD_ITALIC = 'OpenSans_Condensed-ExtraBoldItalic',
    OSANS_CONDENSED_LIGHT = 'OpenSans_Condensed-Light',
    OSANS_CONDENSED_LIGHT_ITALIC = 'OpenSans_Condensed-LightItalic',
    OSANS_CONDENSED_MEDIUM = 'OpenSans_Condensed-Medium',
    OSANS_CONDENSED_REGULAR = 'OpenSans_Condensed-Regular',
    OSANS_CONDENSEDSEMI_BOLD = 'OpenSans_Condensed-SemiBold',
    OSANS_CONDENSEDSEMI_BOLD_ITALIC = 'OpenSans_Condensed-SemiBoldItalic',
    OSANS_SEMICONDENSED_ITALIC = 'OpenSans_SemiCondensed-Italic',
    OSANS_SEMICONDENSED_BOLD = 'OpenSans_SemiCondensed-Bold',
    OSANS_SEMICONDENSED_BOLD_ITALIC = 'OOpenSans_SemiCondensed-BoldItalic',
    OSANS_SEMICONDENSED_EXTRA_BOLD = 'OpenSans_SemiCondensed-ExtraBold',
    OSANS_SEMICONDENSED_EXTRA_BOLD_ITALIC = 'OpenSans_SemiCondensed-ExtraBoldItalic',
    OSANS_SEMICONDENSED_LIGHT = 'OpenSans_SemiCondensed-Light',
    OSANS_SEMICONDENSED_LIGHT_ITALIC = 'OpenSans_SemiCondensed-LightItalic',
    OSANS_SEMICONDENSED_MEDIUM = 'OpenSans_SemiCondensed-Medium',
    OSANS_SEMICONDENSED_REGULAR = 'OpenSans_SemiCondensed-Regular',
    OSANS_SEMICONDENSED_MEDIUM_ITALIC = 'OpenSans_SemiCondensed-MediumItalic',
    OSANS_SEMICONDENSED_SEMIBOLD = 'OpenSans_SemiCondensed-SemiBold',
    OSANS_SEMICONDENSED_SEMIBOLD_ITALIC = 'OpenSans_SemiCondensed-SemiBoldItalic',
    OSANS_BOLD = 'OpenSans-Bold',
    OSANS_BOLD_ITALIC = 'OpenSans-BoldItalic',
    OSANS_EXTRA_BOLD = 'OpenSans-ExtraBold',
    OSANS_EXTRA_BOLD_ITALIC = 'OpenSans-ExtraBoldItalic',
    OSANS_Italic_VARIABLE = 'OpenSans-Italic-VariableFont_wdth,wght',
    OSANS_ITALIC = 'OpenSans-Italic',
    OSANS_LIGHT = 'OpenSans-Light',
    OSANS_LIGHT_ITALIC = 'OpenSans-LightItalic',
    OSANS_MEDIUM = 'OpenSans-Medium',
    OSANS_MEDIUM_ITALIC = 'OpenSans-MediumItalic',
    OSANS_REGULAR = 'OpenSans-Regular',
    OSANS_SEMIBOLD = 'OpenSans-SemiBold',
    OSANS_SEMIBOLD_ITALIC = 'OpenSans-SemiBoldItalic',
    OSANS_VARIABLE = 'OpenSans-VariableFont_wdth,wght',
}


export const enum FontsROBOTO {
    ROBOTO_BLACK = 'Roboto-Black',
    ROBOTO_BLACK_ITALIC = 'Roboto-BlackItalic',
    ROBOTO_BOLD = 'Roboto-Bold',
    ROBOTO_BOLD_ITALIC = 'Roboto-BoldItalic',
    ROBOTO_ITALIC = 'Roboto-Italic',
    ROBOTO_LIGHT = 'Roboto-Light',
    ROBOTO_LIGHT_ITALIC = 'Roboto-LightItalic',
    ROBOTO_MEDIUM = 'Roboto-Medium',
    ROBOTO_MEDIUM_ITALIC = 'Roboto-MediumItalic',
    ROBOTO_REGULAR = 'Roboto-Regular',
    ROBOTO_THIN = 'Roboto-Thin',
    ROBOTO_THIN_ITALIC = 'Roboto-ThinItalic',
}