import IconBack from '../assets/svg/back.svg';
import IconSearch from '../assets/svg/search.svg';
import IconAbout from '../assets/svg/about.svg';
import IconAdd from '../assets/svg/add.svg';
import IconAvatar from '../assets/svg/avatar.svg';
import IconBell from '../assets/svg/bell.svg';
import IconCanceLBorder from '../assets/svg/cancelBorder.svg';
import IconChat from '../assets/svg/chat.svg';
import IconCheck from '../assets/svg/check.svg';
import IconLogoApple from '../assets/svg/LogoApple.svg';
import IconMenu from '../assets/svg/menu.svg';
import IconMenuOrder from '../assets/svg/order.svg';
import IconOrderCancelled from '../assets/svg/ordercancelled.svg';
import IconShowPassword from '../assets/svg/showpassword.svg';
import IconHidePassword from '../assets/svg/hidepassword.svg';
import IconToggleSwitch from '../assets/svg/toggleswitchoff.svg';
import IconWaitOrder from '../assets/svg/waitorder.svg';
import IconWaitPickup from '../assets/svg/waitpickup.svg';
import IconWaitShipper from '../assets/svg/waitshipper.svg';
import IconDateofBirth from '../assets/svg/dateofbirth.svg';
import IconGender from '../assets/svg/gender.svg';
import IconProtect from '../assets/svg/protect.svg';
import IconProduct from '../assets/svg/product.svg';
import IconChange from '../assets/svg/change.svg';
import IconShoppingCart from '../assets/svg/shoppingcart.svg';
import IconShare from '../assets/svg/share.svg';
import IconHeart from '../assets/svg/heart.svg';
import IconHeartChecked from '../assets/svg/heartChecked.svg';
import IconAccount from '../assets/svg/account.svg';
import IconQuestion from '../assets/svg/question.svg';
import IconDown from '../assets/svg/down.svg';
import IconPlus from '../assets/svg/plus.svg';
import IconMinus from '../assets/svg/minus.svg';
import IconClose from '../assets/svg/close.svg';
import IconTrash from '../assets/svg/trash.svg';
import IconLocation from '../assets/svg/location.svg';
import IconVoucher from '../assets/svg/voucher.svg';
import IconPayment from '../assets/svg/payment.svg';
import IconInvoice from '../assets/svg/invoice.svg';
import PaymentAtHome from '../assets/svg/PaymentAtHome.svg';
import PaymentBanking from '../assets/svg/PaymentBanking.svg';
import PayTransfer from '../assets/svg/PayTransfer.svg';
import PaymentInstallment from '../assets/svg/PaymentInstallment.svg';
import PaymentCancell from '../assets/svg/PaymentCancell.svg';
import PaymentPending from '../assets/svg/paymentpending.svg';
import PaymentSuccess from '../assets/svg/paymentsuccess.svg';
import IconStore from '../assets/svg/store.svg';
import All from '../assets/svg/all.svg';
import Create from '../assets/svg/create.svg';
import Delete from '../assets/svg/delete.svg';
import Edit from '../assets/svg/edit.svg';
import IconVideo from '../assets/svg/video.svg'
import IconCamera from '../assets/svg/camera.svg'
import IconSelectAll from '../assets/svg/selectall.svg'
import IconEmoji from '../assets/svg/emoji.svg'
import IconLibraryImage from '../assets/svg/libraryimage.svg'
import IconSend from '../assets/svg/send.svg'
import IconMic from '../assets/svg/mic.svg'
import IconPause from '../assets/svg/pause.svg'
import IconPlay from   '../assets/svg/play.svg'

export class Icon {
    static BackSVG = IconBack;
    static SearchSVG = IconSearch;
    static AboutSVG = IconAbout;
    static AddSVG = IconAdd;
    static AvatarSVG = IconAvatar;
    static BellSVG = IconBell;
    static CanceLBorderSVG = IconCanceLBorder;
    static ChatSVG = IconChat;
    static CheckSVG = IconCheck;
    static LogoAppleSVG = IconLogoApple;
    static MenuSVG = IconMenu;
    static MenuOrderSVG = IconMenuOrder;
    static OrderCancelledSVG = IconOrderCancelled;
    static ShowPasswordSVG = IconShowPassword;
    static HidePasswordSVG = IconHidePassword;
    static ToggleSwitchSVG = IconToggleSwitch;
    static WaitOrderSVG = IconWaitOrder;
    static WaitPickupSVG = IconWaitPickup;
    static WaitShipperSVG = IconWaitShipper;
    static DateofBirthSVG = IconDateofBirth;
    static GenderSVG = IconGender;
    static ProtectSVG = IconProtect;
    static ProductSVG = IconProduct;
    static ChangeSVG = IconChange;
    static ShoppingCartSVG = IconShoppingCart;
    static ShareSVG = IconShare;
    static HeartSVG = IconHeart;
    static HeartCheckedSVG = IconHeartChecked;
    static AccountSVG = IconAccount;
    static QuestionSVG = IconQuestion;
    static DownSVG = IconDown;
    static PlusSVG = IconPlus;
    static MinusSVG = IconMinus;
    static CloseSVG = IconClose;
    static TrashSVG = IconTrash;
    static LocationSVG = IconLocation;
    static VoucherSVG = IconVoucher;
    static PaymentSVG = IconPayment;
    static InvoiceSVG = IconInvoice;
    static PaymentAtHomeSVG = PaymentAtHome;
    static PaymentBankingSVG = PaymentBanking;
    static PayTransferSVG = PayTransfer;
    static PaymentInstallmentSVG = PaymentInstallment;
    static PaymentCancellSVG = PaymentCancell;
    static PaymentPendingSVG = PaymentPending;
    static PaymentSuccessSVG = PaymentSuccess;
    static StoreSVG = IconStore;
    static AllSVG = All;
    static CreateSVG = Create;
    static DeleteSVG = Delete;
    static EditSVG = Edit;
    static VideoSVG = IconVideo;
    static CameraSVG = IconCamera;
    static SelectAllSVG = IconSelectAll;
    static EmojiSVG = IconEmoji;
    static LibraryImageSVG = IconLibraryImage;
    static SendSVG = IconSend;
    static MicSVG = IconMic;
    static PauseSVG = IconPause;
    static PlaySVG = IconPlay;
    static HOME = require('../assets/images/house.png');
    static CART = require('../assets/images/cart.png');
    static CATEGORY = require('../assets/images/category.png');
    static INFOR = require('../assets/images/infor.png');
    static RIGHT = require('../assets/images/right.png');
    static LOYALCUSTOMER = require('../assets/images/customervip.png');
    static PROFILE = require('../assets/images/profile.png');
    static ADDRESS = require('../assets/images/address.png');
    static FAVOURITE = require('../assets/images/favourite.png');
    static CHANGEPASSWORD = require('../assets/images/changepassword.png');
    static FEEDBACK = require('../assets/images/feedback.png');
    static CHATWITHSHOP = require('../assets/images/chatwithshop.png');
    static DELETEUSER = require('../assets/images/deleteuser.png');
    static CONTACT = require('../assets/images/contact.png');
    static INTRODUCE = require('../assets/images/introduce.png');
    static LOGOUT = require('../assets/images/logout.png');
    static LOGIN = require('../assets/images/login.png');
    static DELETEACCOUNT = require('../assets/images/deleteacount.jpg');
    static CALL = require('../assets/images/call.png');
    static WEBSITE = require('../assets/images/website.png');
    static CONTACTFEEDBACK = require('../assets/images/contactfeedback.png');
    static EMAIL = require('../assets/images/email.png');
    static BACKGROUNDSTORE = require('../assets/images/backgroundstore.png');
    static GOOGLE = require('../assets/images/google.png');
    static ZALO = require('../assets/images/zalo.png');
    static FACEBOOK = require('../assets/images/facebook.png');
    static CANCELSEARCH = require('../assets/images/canecelSearch.png');
    static NotFoundProduct = require('../assets/images/NotfoundProduct.png');
    static NoCarts = require('../assets/images/NoCarts.png');
    static BACKGROUNDVOUCHER = require('../assets/images/backgroundVoucher.png');
    static PAYMENTVNPAY = require('../assets/images/Vnpay.png');
    static CATEGORYADMIN = require('../assets/images/categoryAdmin.png');
    static PRODUCTADMIN = require('../assets/images/product.png');
    static BANNERADMIN = require('../assets/images/advertising.png');
    static CUSTOMERADMIN = require('../assets/images/customer.png');
    static POINTS = require('../assets/images/points.png');
    static NOSEARCHORDER = require('../assets/images/nosearchorder.png');
}



export const Lottie = {
    Loading: require('../assets/lottie/loading.json'),
}
